"""ai_task_lease

Revision ID: dcde8273c8de
Revises: bf3920863075
Create Date: 2026-09-17 21:31:13.328174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcde8273c8de'
down_revision: Union[str, Sequence[str], None] = 'bf3920863075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ai_task', sa.String(length=40), nullable=True))
    op.add_column('applications', sa.Column('ai_task_started_at', sa.DateTime(), nullable=True))
    op.create_index('uq_active_token_issue', 'candidate_token_issues', ['application_id'], unique=True, sqlite_where=sa.text('invalidated_at IS NULL'), postgresql_where=sa.text('invalidated_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_token_issue', table_name='candidate_token_issues', sqlite_where=sa.text('invalidated_at IS NULL'), postgresql_where=sa.text('invalidated_at IS NULL'))
    op.drop_column('applications', 'ai_task_started_at')
    op.drop_column('applications', 'ai_task')
    # ### end Alembic commands ###
